### ISSUE TITLE
The terminology in this lesson is somewhat inconsistent

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sinatra-routes-readme#20]
Hi. Let me start off by saying that I got the gist of this lesson, and I was able to understand how routes work with regards to MVC and the request/response cycle.

That said, I had trouble understanding what a route specifically WAS. The lesson at different points seemed to indicate that it was the path (`'/medicines'`, for example), or `get '/medicines'`, or the entire `get '/medicines' do {...}` controller action/block.

I get that this stuff can overlap (like "controller action" referring to both the `get...do {...}` block and the action itself). And again, at the very least I understand the PURPOSE of a route and how it fits into everything, but I was hoping for a clearer understanding of what's what. 

Thanks for looking into this!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
