### ISSUE TITLE
Make purpose of Routes more explicit

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/sinatra-routes-readme#7]
This currently doesn't really address the routing aspect of routes - of connecting a URL to a particular part of our application, that the URL is the interface. Plus it's getting into REST and complex AR examples.

**Comment by AnnJohn** [comment]
Also per @dfenjves- Explain how params can be generated using dynamic urls

**Comment by aviflombaum** [comment]
I don't think we should be introducing dynamic routes or params in this readme. It's single purpose is to explain how we map urls to application code. I think params belongs in another readme and dynamic routes in another one (which should also mention query string and params)

**Comment by AnnJohn** [comment]
@dfenjves ^^

**Comment by dfenjves** [comment]
Agree with Avi - this is the first routes lesson, not the dynamic routes lesson. I'll work on that one.
