### ISSUE TITLE
simplify

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sinatra-routes-readme#9]
needs to be pared back a bit. students won't have learned about view rendering, erb, file structure. for now we should show routes just rendering static strings. 

@aviflombaum @AnnJohn

**Comment by AnnJohn** [comment]
@aviflombaum ^^

**Comment by dfenjves** [comment]
Agree with this - it's a great explanation, but I think this should be about rendering static pages or strings.
